import json
from pathlib import Path

from sncp_ppo.run_readiness import verify_v16_run_ready, write_readiness_report


def _source_text(cell):
    source = cell.get("source", "")
    return "".join(source) if isinstance(source, list) else source


def test_v37_probe_run_readiness_passes_current_repo():
    summary = verify_v16_run_ready(Path("."))

    assert summary.status == "pass"
    assert summary.training_cell_found is True
    assert summary.evaluation_cell_found is True
    assert summary.baseline_densities == ()


def test_v37_probe_run_readiness_flags_stale_notebook(tmp_path):
    # A stale notebook that still launches a versioned full-run must be flagged:
    # the current Colab entry point is the v37 paired probe.
    notebook = {
        "cells": [
            {
                "cell_type": "code",
                "source": "SAVE_PATH = 'checkpoints/sncp_ppo_v36.pt'\n",
            },
            {
                "cell_type": "code",
                "source": "CHECKPOINT = 'checkpoints/sncp_ppo_v36.pt'\ncmd = ['python', 'scripts/run_post_eval.py']\n",
            },
        ]
    }
    (tmp_path / "sncp_ppo_colab.ipynb").write_text(json.dumps(notebook), encoding="utf-8")
    scripts_dir = tmp_path / "scripts"
    scripts_dir.mkdir()
    (scripts_dir / "run_v37_probes.py").write_text("stub\n", encoding="utf-8")
    scratch_dir = tmp_path / "scratch"
    scratch_dir.mkdir()
    (scratch_dir / "_analyze_v37_probe.py").write_text("stub\n", encoding="utf-8")

    summary = verify_v16_run_ready(tmp_path)

    assert summary.status == "fail"
    assert any("v37 probe training" in note for note in summary.notes)
    assert any("v37 probe analysis" in note for note in summary.notes)


def test_write_readiness_report(tmp_path):
    summary = verify_v16_run_ready(Path("."))
    output = tmp_path / "readiness.md"

    write_readiness_report(summary, output)

    report = output.read_text(encoding="utf-8")
    assert "Overall status: pass" in report
    assert "Baseline densities: n/a" in report


# v24+ deliberately dropped the separate preflight cell; the readiness report is now
# auto-generated by the eval pipeline (run_v16_post_eval) instead of a notebook cell, so
# the old "preflight cell before training" test no longer applies and was removed.


def test_colab_persist_cell_downloads_eval_v37_probe_artifact_bundle():
    notebook = json.loads(Path("sncp_ppo_colab.ipynb").read_text(encoding="utf-8"))
    code_sources = [
        _source_text(cell)
        for cell in notebook["cells"]
        if cell.get("cell_type") == "code"
    ]
    persist_cells = [source for source in code_sources if "DOWNLOAD = False" in source]

    assert len(persist_cells) == 1
    persist_cell = persist_cells[0]
    assert "shutil.make_archive" in persist_cell
    assert "'eval_v37_probe_artifacts'" in persist_cell
    assert "'eval_v37_probe'" in persist_cell
    assert "files.download(archive)" in persist_cell
